function mpSetup(all=true){
 eqSetup();save.legendary={version:1,cleared:[],caught:[],active:null};save.tower=undefined;
 save.badges=all?[0,1,2,3,4,5,6,7]:[];save.journey.championDefeated=all;
 save.routeChain={cursor:1,lines:0,mode:'story',visitedCursors:all?ROUTE_CHAIN_NODES.map((_,i)=>i):[1]};
 adventureFlyUnlocked=true;save.trainingMode=null;save.townStop=null;clearControlsScreens();hideOverlay();paused=false;updateHUD();
}
function mpOpen(){openFlyMap();renderFlyDestinations();drawFlyMap();}
function mpFits(el){const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;}
function mpPoint(t){const c=$('flyMapCanvas'),r=c.getBoundingClientRect(),sx=r.width/c.offsetWidth,sy=r.height/c.offsetHeight;return {clientX:r.left+(c.clientLeft+c.clientWidth*t.x/240)*sx,clientY:r.top+(c.clientTop+c.clientHeight*t.y/190)*sy};}
$('qaRun').textContent='Run pixel map QA';$('qaGary').textContent='Preview Fly map';$('qaReward').textContent='Preview minimap';$('qaFinale').textContent='Preview town Pikachu';
function mpDemo(){comfortSettings.reducedMotion=false;setInterval(()=>{qaNow+=110;pixelMapAnimate();},110);}
$('qaGary').onclick=async()=>{mpSetup();await Promise.all([pixelMapArtReady,pixelMapPikachuReady]);mpOpen();$('qaPanel').hidden=true;mpDemo();};
$('qaReward').onclick=async()=>{mpSetup();await Promise.all([pixelMapArtReady,pixelMapPikachuReady]);routeChainStartAtCursor(routeChainCursorForRoute('ROUTE 9'),'training',null);clearControlsScreens();paused=true;hideOverlay();compactFit();drawBoard();drawNext();updateHUD();$('qaPanel').hidden=true;mpDemo();};
$('qaFinale').onclick=async()=>{mpSetup();await Promise.all([pixelMapArtReady,pixelMapPikachuReady]);travelToFlyTarget(flyTargets().find(t=>pixelMapTargetKey(t)==='CERULEAN CITY'));clearControlsScreens();mpOpen();$('qaPanel').hidden=true;};
$('qaRun').onclick=async()=>{
 $('qaRun').disabled=true;eqResults.length=0;const stored=new Map(Object.keys(localStorage).map(k=>[k,localStorage.getItem(k)])),oldReducedMotion=comfortSettings.reducedMotion;
 try{
 await eqCase('Embedded artwork decodes offline for both maps',async()=>{mpSetup();eqAssert(await pixelMapArtReady,'Image failed');eqAssert(KANTO_PIXEL_MAP_ART.startsWith('data:image/png;base64,'),'External art');drawKantoMap();mpOpen();eqAssert($('kantoMap').dataset.mapArt==='ready'&&$('flyMapCanvas').dataset.mapArt==='ready','Maps not using approved art');});
 await eqCase('Pikachu sprites decode offline with transparent backgrounds',async()=>{mpSetup();eqAssert(await pixelMapPikachuReady,'Sprite failed');eqAssert(KANTO_PIKACHU_RUN_ART.startsWith('data:image/png;base64,')&&KANTO_PIKACHU_SIT_ART.startsWith('data:image/png;base64,'),'External sprite');for(const c of [pixelMapPikachuRun,pixelMapPikachuSit])eqAssert(c.getContext('2d').getImageData(0,0,1,1).data[3]===0,'Solid sprite background');});
 await eqCase('Pikachu visibly runs in both maps without changing the current route',()=>{mpSetup();comfortSettings.reducedMotion=false;drawKantoMap();const mini=$('kantoMap').toDataURL(),cursor=save.routeChain.cursor;qaNow+=110;pixelMapAnimate();eqAssert($('kantoMap').dataset.markerMotion==='running'&&$('kantoMap').toDataURL()!==mini,'Mini does not animate');mpOpen();const fly=$('flyMapCanvas').toDataURL();qaNow+=110;pixelMapAnimate();eqAssert($('flyMapCanvas').toDataURL()!==fly&&save.routeChain.cursor===cursor,'Fly animation or progression wrong');});
 await eqCase('Pikachu sits still at a town in both maps',()=>{mpSetup();travelToFlyTarget(flyTargets().find(t=>pixelMapTargetKey(t)==='CERULEAN CITY'));clearControlsScreens();drawKantoMap();mpOpen();const before=[$('kantoMap').toDataURL(),$('flyMapCanvas').toDataURL()];qaNow+=110;drawKantoMap();drawFlyMap();eqAssert(['kantoMap','flyMapCanvas'].every((id,i)=>$(id).dataset.markerMotion==='sitting'&&$(id).dataset.location==='CERULEAN CITY'&&$(id).toDataURL()===before[i]),'Town pose moved or wrong location');});
 await eqCase('Reduced motion keeps Pikachu visible and stationary on routes',()=>{mpSetup();comfortSettings.reducedMotion=true;drawKantoMap();mpOpen();const before=[$('kantoMap').toDataURL(),$('flyMapCanvas').toDataURL()];qaNow+=110;drawKantoMap();drawFlyMap();eqAssert(['kantoMap','flyMapCanvas'].every((id,i)=>$(id).dataset.markerMotion==='idle'&&$(id).toDataURL()===before[i]),'Reduced motion ignored');comfortSettings.reducedMotion=false;});
 await eqCase('Every GBA town and Routes 1–25 are represented exactly once',()=>{mpSetup();const t=flyTargets(),cities=t.filter(n=>n.kind==='city');eqAssert(cities.length===11,'Town count '+cities.length);for(let i=1;i<=25;i++)eqAssert(t.filter(n=>n.route==='ROUTE '+i).length===1,'Missing/duplicate route '+i);eqAssert(new Set(t.map(pixelMapTargetKey)).size===t.length,'Duplicate target');});
 await eqCase('Pallet, Lavender, Indigo and all other towns use canonical geography',()=>{mpSetup();for(const c of KANTO_PIXEL_MAP.cities){const t=flyTargets().find(n=>pixelMapTargetKey(n)===c.name);eqAssert(t&&t.x===c.x&&t.y===c.y,'Misplaced '+c.name);}eqAssert(pixelMapLocation('PALLET TOWN').x===60&&pixelMapLocation('PALLET TOWN').y===133,'Pallet reference');eqAssert(pixelMapLocation('LAVENDER TOWN').x===214,'Lavender reference');});
 await eqCase('Every marker center selects its own destination, including adjacent landmarks',()=>{mpSetup();for(const t of flyTargets())eqAssert(pixelMapTargetKey(flyHitTargetAt(t.x,t.y))===pixelMapTargetKey(t),'Wrong hit '+pixelMapTargetKey(t));eqAssert(!flyHitTargetAt(-1,45)&&!flyHitTargetAt(240,0),'Outside hit');});
 await eqCase('Click coordinates stay aligned with the fitted canvas and borders',()=>{mpSetup();mpOpen();for(const t of flyTargets()){const p=flyCanvasPoint(mpPoint(t));eqAssert(Math.abs(p.x-t.x)<.01&&Math.abs(p.y-t.y)<.01,'Scaled hit '+pixelMapTargetKey(t));}});
 await eqCase('Unvisited destinations and stale available targets cannot travel',()=>{mpSetup(false);const t=flyTargets().find(n=>n.route==='ROUTE 9'),before=save.routeChain.cursor;eqAssert(t&&!t.available,'Expected locked');travelToFlyTarget({...t,available:true});eqAssert(save.routeChain.cursor===before,'Unlock bypass');mpOpen();eqAssert([...$('flyDestinations').children].some(b=>b.disabled&&b.textContent.includes('ROUTE 9')),'Locked button enabled');});
 await eqCase('Map-only Route 11 is visible without inventing a campaign stop',()=>{mpSetup();const t=flyTargets().find(n=>n.route==='ROUTE 11'),before=save.routeChain.cursor;eqAssert(t?.referenceOnly&&!t.available,'Missing reference');travelToFlyTarget({...t,available:true});eqAssert(save.routeChain.cursor===before,'Reference changed progression');});
 await eqCase('Clicking a visited route flies through the existing progression system',()=>{mpSetup();mpOpen();const t=flyTargets().find(n=>n.route==='ROUTE 9');$('flyMapCanvas').dispatchEvent(new MouseEvent('click',{bubbles:true,...mpPoint(t)}));eqAssert(save.routeChain.cursor===routeChainCursorForRoute('ROUTE 9')&&currentRoute()==='ROUTE 9','Wrong route');eqAssert(!isShown('flyModal'),'Fly stayed open');drawKantoMap();eqAssert($('kantoMap').dataset.location==='ROUTE 9','Player did not move');validateBackupRun(runSnapshot(),'adventure');});
 await eqCase('Clicking Lavender goes to Lavender, retaining its real town checkpoint',()=>{mpSetup();mpOpen();const t=flyTargets().find(n=>pixelMapTargetKey(n)==='LAVENDER TOWN');eqAssert(t.available,'Lavender locked');travelToFlyTarget(t);eqAssert(save.townStop?.chainCursor===t.chainCursor,'Town changed');eqAssert(pixelMapCurrentLocation().name==='LAVENDER TOWN','Wrong player location');validateBackupRun(runSnapshot(),'adventure');});
 await eqCase('Current position follows a saved route and a saved town after reload',()=>{mpSetup();const t=flyTargets().find(n=>pixelMapTargetKey(n)==='CERULEAN CITY');travelToFlyTarget(t);const snap=runSnapshot();restoreRunSnapshot(snap,'adventure');drawKantoMap();eqAssert($('kantoMap').dataset.location==='CERULEAN CITY','Town restore');clearControlsScreens();save.townStop=null;routeChainStartAtCursor(routeChainCursorForRoute('ROUTE 19'),'training',null);const route=runSnapshot();restoreRunSnapshot(route,'adventure');drawKantoMap();eqAssert($('kantoMap').dataset.location==='ROUTE 19','Route restore');});
 await eqCase('Map rendering does not rewrite route-chain geography, order or saved progress',()=>{mpSetup();const nodes=JSON.stringify(ROUTE_CHAIN_NODES),chain=JSON.stringify(save.routeChain);drawKantoMap();mpOpen();eqAssert(nodes===JSON.stringify(ROUTE_CHAIN_NODES)&&chain===JSON.stringify(save.routeChain),'Map mutated progression');});
 await eqCase('Controller focus highlights and selects a visited destination',()=>{mpSetup();mpOpen();eqPad([]);const targets=flyTargets(),i=targets.findIndex(n=>n.route==='ROUTE 12'),b=$('flyDestinations').children[i];focusMenuElement(b,$('flyModal'));eqAssert(flyHoverTarget?.route==='ROUTE 12','Focus missing');eqTap(0);eqAssert(currentRoute()==='ROUTE 12','Controller selection failed');});
 await eqCase('Labels toggle preserves Pikachu and never adds an arrow or location banner',()=>{mpSetup();mpOpen();const before=$('flyMapCanvas').dataset.location;const was=pixelMapLabels;$('pixelMapLabels').click();eqAssert(pixelMapLabels!==was&&$('flyMapCanvas').dataset.location===before&&$('flyMapCanvas').dataset.markerMotion==='running','Toggle broke Pikachu');eqAssert(!/you are here|yellow arrow/i.test($('flyModal').textContent+$('flyMapCanvas').getAttribute('aria-label')),'Unwanted annotation');$('pixelMapLabels').click();});
 await eqCase('Fly map and destination list fit the viewport without stretching',()=>{mpSetup();mpOpen();for(const id of ['flyMapCanvas','flyMapInfo','flyDestinations','pixelMapLabels','flyCloseBtn'])eqAssert(mpFits($(id)),'Offscreen '+id);const c=$('flyMapCanvas');eqAssert(Math.abs(c.clientWidth/c.clientHeight-240/190)<.01,'Stretched map');eqAssert($('flyDestinations').scrollHeight>$('flyDestinations').clientHeight,'List not scrollable');eqAssert(document.documentElement.scrollWidth<=innerWidth,'Page overflow');});
 await eqCase('Last destination remains reachable with a controller at this aspect ratio',()=>{mpSetup();mpOpen();eqPad([]);const b=[...$('flyDestinations').children].filter(b=>!b.disabled).pop();focusMenuElement(b,$('flyModal'));eqAssert(mpFits(b),'Last destination clipped');});
 await eqCase('Minimap remains in the game layout with the approved aspect ratio',()=>{mpSetup();clearControlsScreens();compactFit();drawKantoMap();const c=$('kantoMap');eqAssert(mpFits(c),'Mini offscreen');const r=c.getBoundingClientRect();eqAssert(Math.abs((r.width-4)/(r.height-4)-240/190)<.04,'Mini stretched');});
 await eqCase('Gym battles retain their battle display and block map travel',()=>{mpSetup();const t=flyTargets().find(n=>n.route==='ROUTE 9');save.gymBattle=campaignNewBattle(0);loadGymPokemon(0);beginGymFight();const cursor=save.routeChain.cursor;drawKantoMap();eqAssert($('mapTitle').textContent!=='KANTO MAP','Gym replaced');travelToFlyTarget(t);eqAssert(save.routeChain.cursor===cursor,'Battle escaped');});
 }finally{comfortSettings.reducedMotion=oldReducedMotion;activeAdventureSlot=1;clearControlsScreens();cancelCampaignTransition();for(const k of Object.keys(localStorage))localStorage.removeItem(k);for(const [k,v]of stored)localStorage.setItem(k,v);}
 $('qaResults').textContent=JSON.stringify({version:'1.8.10',viewport:[innerWidth,innerHeight],passed:eqResults.filter(t=>t.result==='PASS').length,failed:eqResults.filter(t=>t.result==='FAIL').length,tests:eqResults},null,2);$('qaRun').disabled=false;
};
